version: '3'
services:
    qobuz:
        image: docker-qobuz
        ports:
            - 8080:8080
        environment:
            - QOBUZNAME=92onntgz9l@aakkmail.com
            - QOBUZPASS=Mexico2025
        restart: unless-stopped
