version: '3'
services:
    qobuz:
        image: docker-qobuz
        ports:
            - 8080:8080
        environment:
            - QOBUZNAME=jo3ksg2ppv@aakk.link
            - QOBUZPASS=Mexico2025
        restart: unless-stopped
